### ISSUE TITLE
Stacking race and grid objects with stacks() causes member names to be unexpected.

### ISSUE THREAD

**Issue by amazongodman** [tidymodels/stacks#93]
Stacking race and grid objects with stacks() causes member names to be unexpected.

Creating a reca object

```
library(tidymodels)
library(finetune)
library(stacks)

data(two_class_dat, package = "modeldata")

set.seed(123)
folds <- bootstraps(two_class_dat, times = 10)

rf_spec <- rand_forest(mtry = tune(), trees = tune(), min_n = tune()) %>%
  set_mode("classification") %>%
  set_engine("ranger")

rf_wf <- workflow(Class ~ ., rf_spec)
ctrl_stck <- control_race(save_pred = TRUE, save_workflow = TRUE)

doParallel::registerDoParallel()
set.seed(234)
race_res <- tune_race_anova(rf_wf, 
                            resamples = folds, 
                            grid = 10, 
                            control = ctrl_stck)
```

Creating a tune_grid object

```
glmnet_recipe <- 
  recipe(formula = Class ~ ., data = two_class_dat) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_predictors(), -all_nominal()) 
glmnet_spec <- 
  logistic_reg(penalty = tune(), mixture = tune()) %>% 
  set_mode("classification") %>% 
  set_engine("glmnet") 
glmnet_workflow <- 
  workflow() %>% 
  add_recipe(glmnet_recipe) %>% 
  add_model(glmnet_spec) 
glmnet_grid <- tidyr::crossing(penalty = 10^seq(-6, -1, length.out = 20), mixture = c(0.05, 
                                                                                      0.2, 0.4, 0.6, 0.8, 1)) 
glmnet_tune <- 
  tune_grid(glmnet_workflow,
            resamples = folds, 
            grid = glmnet_grid) 
glmnet_tune <- 
  tune_grid(glmnet_workflow,
            resamples = folds, 
            grid = glmnet_grid,
            control = control_grid(save_pred = T,save_workflow = T)) 
```

If I handle two(race + tune_grid) of them in stacks(), the behaviour will be wrong.

```
stack_model <- 
  stacks() %>%
  add_candidates(race_res,name="race") %>% 
  add_candidates(glmnet_tune,name="tune")

Warning message:
Predictions from 116 candidates were identical to those from existing
* candidates and were removed from the data stack. 

stack_model
# A data stack with 2 model definitions and 63 candidate members:
#   race: 1 model configuration
#   tune: 62 model configurations
# Outcome: Class (factor)

fit_stack <- stack_model %>% 
  blend_predictions() %>% 
  fit_members()

fit_stack
-- A stacked ensemble model -------------------------------------

Out of 63 possible candidate members, the ensemble retained 4.
Penalty: 0.1.
Mixture: 1.

The 4 highest weighted member classes are:
# A tibble: 4 x 3
  member                  type          weight
  <chr>                   <chr>          <dbl>
1 .pred_Class2_tune_1_001 logistic_reg 3.05   
2 .pred_Class2_race_1_03  rand_forest  0.244  
3 .pred_Class2_tune_1_021 logistic_reg 0.106  
4 .pred_Class2_tune_1_031 logistic_reg 0.00265

fit_stack %>% 
  collect_parameters(stack=fit_stack, 
                     candidates=".pred_Class2_race_1_03")
Error: The `candidates` argument to `collect_parameters()` must be the name given
* to a set of candidates added with `add_candidates()`.
Run `rlang::last_error()` to see where the error occurred.

fit_stack %>% 
  collect_parameters(stack=fit_stack, 
                     candidates="race")
# A tibble: 10 x 5
   member     mtry trees min_n  coef
   <chr>     <int> <int> <int> <dbl>
 1 race_1_01     1  1595    24    NA
 2 race_1_02     1   532    11    NA
 3 race_1_03     1  1168    33    NA
 4 race_1_04     2    58    32    NA
 5 race_1_05     1   850    15    NA
```

Do you know the cause of this?
thank you.

**Comment by simonpcouch** [comment]
Thanks for the issue @amazongodman. Could you provide your `sessionInfo()`? This looks similar to prior issues that I believe have been addressed, though I may be wrong. :-)

**Comment by amazongodman** [comment]
Thanks for your comment.

how about my session ?

```
> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

other attached packages:
 [1] finetune_0.1.0     ranger_0.13.1      glmnet_4.1-2       Matrix_1.3-4      
 [5] vctrs_0.3.8        rlang_0.4.11       xgboost_1.4.1.1    forcats_0.5.1     
 [9] stringr_1.4.0      readr_2.0.2        tidyverse_1.3.1    yardstick_0.0.8   
[13] workflowsets_0.1.0 workflows_0.2.4    tune_0.1.6.9000    tidyr_1.1.4       
[17] tibble_3.1.5       rsample_0.1.0      recipes_0.1.17     purrr_0.3.4       
[21] parsnip_0.1.7      modeldata_0.1.1    infer_1.0.0        ggplot2_3.3.5     
[25] dplyr_1.0.7        dials_0.0.10       scales_1.1.1       broom_0.7.9       
[29] tidymodels_0.1.4   stacks_0.2.1      

loaded via a namespace (and not attached):
  [1] readxl_1.3.1         backports_1.2.1      plyr_1.8.6           igraph_1.2.7        
  [5] splines_4.1.1        crosstalk_1.1.1      listenv_0.8.0        usethis_2.1.2       
  [9] rstantools_2.1.1     inline_0.3.19        digest_0.6.28        butcher_0.1.5       
 [13] foreach_1.5.1        htmltools_0.5.2      rsconnect_0.8.24     fansi_0.5.0         
 [17] magrittr_2.0.1       doParallel_1.0.16    tzdb_0.1.2           globals_0.14.0      
 [21] modelr_0.1.8         gower_0.2.2          RcppParallel_5.1.4   matrixStats_0.61.0  
 [25] xts_0.12.1           hardhat_0.1.6        prettyunits_1.1.1    colorspace_2.0-2    
 [29] rvest_1.0.2          haven_2.4.3          callr_3.7.0          crayon_1.4.1        
 [33] jsonlite_1.7.2       lme4_1.1-27.1        survival_3.2-11      zoo_1.8-9           
 [37] iterators_1.0.13     glue_1.4.2           gtable_0.3.0         ipred_0.9-12        
 [41] V8_3.4.2             pkgbuild_1.2.0       rstan_2.21.2         shape_1.4.6         
 [45] future.apply_1.8.1   DBI_1.1.1            ggthemes_4.2.4       miniUI_0.1.1.1      
 [49] Rcpp_1.0.7           xtable_1.8-4         GPfit_1.0-8          stats4_4.1.1        
 [53] lava_1.6.10          StanHeaders_2.21.0-7 prodlim_2019.11.13   DT_0.19             
 [57] httr_1.4.2           htmlwidgets_1.5.4    threejs_0.3.3        ellipsis_0.3.2      
 [61] farver_2.1.0         pkgconfig_2.0.3      loo_2.4.1            dbplyr_2.1.1        
 [65] nnet_7.3-16          utf8_1.2.2           labeling_0.4.2       tidyselect_1.1.1    
 [69] DiceDesign_1.9       reshape2_1.4.4       later_1.3.0          cellranger_1.1.0    
 [73] munsell_0.5.0        tools_4.1.1          cli_3.0.1            generics_0.1.1.9000 
 [77] ggridges_0.5.3       fastmap_1.1.0        processx_3.5.2       fs_1.5.0            
 [81] future_1.22.1        nlme_3.1-152         mime_0.12            rstanarm_2.21.1     
 [85] xml2_1.3.2           rstudioapi_0.13      compiler_4.1.1       bayesplot_1.8.1     
 [89] shinythemes_1.2.0    curl_4.3.2           reprex_2.0.1         tidyposterior_0.1.0 
 [93] lhs_1.1.3            stringi_1.7.5        ps_1.6.0             lattice_0.20-44     
 [97] nloptr_1.2.2.2       markdown_1.1         shinyjs_2.0.0        pillar_1.6.4        
[101] lifecycle_1.0.1      furrr_0.2.3          data.table_1.14.2    httpuv_1.6.3        
[105] R6_2.5.1             promises_1.2.0.1     gridExtra_2.3        parallelly_1.28.1   
[109] codetools_0.2-18     boot_1.3-28          colourpicker_1.1.1   MASS_7.3-54         
[113] gtools_3.9.2         assertthat_0.2.1     withr_2.4.2          shinystan_2.5.0     
[117] hms_1.1.1            parallel_4.1.1       grid_4.1.1           rpart_4.1-15        
[121] timeDate_3043.102    class_7.3-19         minqa_1.2.4          pROC_1.18.0         
[125] shiny_1.7.1          lubridate_1.8.0      base64enc_0.1-3      dygraphs_1.1.1.6    
[129] usemodels_0.1.0     
```

**Comment by simonpcouch** [comment]
Does updating to the dev version of the package via `devtools::install_github("tidymodels/stacks")` fix your issue? If not, could you clarify what you mean when you say "the behavior will be wrong"?

**Comment by amazongodman** [comment]
@simonpcouch 

devtools::install_github("tidymodels/stacks")

I've updated and still have the same problem.


```
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default


attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
 [1] stacks_0.2.1.9000  finetune_0.1.0     yardstick_0.0.8   
 [4] workflowsets_0.1.0 workflows_0.2.4    tune_0.1.6.9000   
 [7] tidyr_1.1.4        tibble_3.1.5       rsample_0.1.0     
[10] recipes_0.1.17     purrr_0.3.4        parsnip_0.1.7     
[13] modeldata_0.1.1    infer_1.0.0        ggplot2_3.3.5     
[16] dplyr_1.0.7        dials_0.0.10       scales_1.1.1      
[19] broom_0.7.9        tidymodels_0.1.4  

loaded via a namespace (and not attached):
 [1] nlme_3.1-152        fs_1.5.0            usethis_2.1.3      
 [4] lubridate_1.8.0     devtools_2.4.2      doParallel_1.0.16  
 [7] DiceDesign_1.9      rprojroot_2.0.2     tools_4.1.1        
[10] backports_1.2.1     utf8_1.2.2          R6_2.5.1           
[13] rpart_4.1-15        DBI_1.1.1           colorspace_2.0-2   
[16] nnet_7.3-16         withr_2.4.2         tidyselect_1.1.1   
[19] prettyunits_1.1.1   processx_3.5.2      curl_4.3.2         
[22] compiler_4.1.1      glmnet_4.1-2        cli_3.0.1          
[25] desc_1.4.0          callr_3.7.0         digest_0.6.28      
[28] minqa_1.2.4         pkgconfig_2.0.3     lme4_1.1-27.1      
[31] parallelly_1.28.1   sessioninfo_1.1.1   lhs_1.1.3          
[34] fastmap_1.1.0       rlang_0.4.11        rstudioapi_0.13    
[37] shape_1.4.6         generics_0.1.1.9000 magrittr_2.0.1     
[40] Matrix_1.3-4        Rcpp_1.0.7          munsell_0.5.0      
[43] fansi_0.5.0         GPfit_1.0-8         lifecycle_1.0.1    
[46] furrr_0.2.3         pROC_1.18.0         MASS_7.3-54        
[49] pkgbuild_1.2.0      plyr_1.8.6          grid_4.1.1         
[52] parallel_4.1.1      listenv_0.8.0       butcher_0.1.5      
[55] crayon_1.4.2        lattice_0.20-44     splines_4.1.1      
[58] ps_1.6.0            pillar_1.6.4        ranger_0.13.1      
[61] boot_1.3-28         future.apply_1.8.1  codetools_0.2-18   
[64] pkgload_1.2.3       glue_1.4.2          remotes_2.4.1      
[67] nloptr_1.2.2.2      vctrs_0.3.8         foreach_1.5.1      
[70] testthat_3.1.0      gtable_0.3.0        future_1.23.0      
[73] assertthat_0.2.1    cachem_1.0.6        gower_0.2.2        
[76] prodlim_2019.11.13  class_7.3-19        survival_3.2-11    
[79] timeDate_3043.102   iterators_1.0.13    memoise_2.0.0      
[82] hardhat_0.1.6       lava_1.6.10         globals_0.14.0     
[85] ellipsis_0.3.2      ipred_0.9-12   
```



I have installed new finetune and rlang



```
R version 4.1.1 (2021-08-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] stacks_0.2.1.9000   finetune_0.1.0.9000 yardstick_0.0.8     workflowsets_0.1.0  workflows_0.2.4     tune_0.1.6.9000    
 [7] tidyr_1.1.4         tibble_3.1.5        rsample_0.1.0       recipes_0.1.17      purrr_0.3.4         parsnip_0.1.7      
[13] modeldata_0.1.1     infer_1.0.0         ggplot2_3.3.5       dplyr_1.0.7         dials_0.0.10        scales_1.1.1       
[19] broom_0.7.9         tidymodels_0.1.4   

loaded via a namespace (and not attached):
 [1] splines_4.1.1       foreach_1.5.1       prodlim_2019.11.13  assertthat_0.2.1    GPfit_1.0-8         globals_0.14.0     
 [7] ipred_0.9-12        pillar_1.6.4        backports_1.2.1     lattice_0.20-44     glue_1.4.2          pROC_1.18.0        
[13] digest_0.6.28       minqa_1.2.4         hardhat_0.1.6       colorspace_2.0-2    Matrix_1.3-4        plyr_1.8.6         
[19] timeDate_3043.102   pkgconfig_2.0.3     lhs_1.1.3           DiceDesign_1.9      listenv_0.8.0       ranger_0.13.1      
[25] gower_0.2.2         lava_1.6.10         lme4_1.1-27.1       generics_0.1.1.9000 usethis_2.1.3       ellipsis_0.3.2     
[31] withr_2.4.2         furrr_0.2.3         nnet_7.3-16         cli_3.0.1           survival_3.2-11     magrittr_2.0.1     
[37] crayon_1.4.2        fs_1.5.0            future_1.23.0       fansi_0.5.0         parallelly_1.28.1   doParallel_1.0.16  
[43] nlme_3.1-152        MASS_7.3-54         class_7.3-19        tools_4.1.1         lifecycle_1.0.1     glmnet_4.1-2       
[49] munsell_0.5.0       compiler_4.1.1      rlang_0.4.12        grid_4.1.1          nloptr_1.2.2.2      iterators_1.0.13   
[55] rstudioapi_0.13     boot_1.3-28         gtable_0.3.0        codetools_0.2-18    DBI_1.1.1           R6_2.5.1           
[61] lubridate_1.8.0     future.apply_1.8.1  utf8_1.2.2          butcher_0.1.5       shape_1.4.6         parallel_4.1.1     
[67] Rcpp_1.0.7          vctrs_0.3.8         rpart_4.1-15        tidyselect_1.1.1   
```



But there is no improvement.

**Comment by amazongodman** [comment]
@simonpcouch 


excuse me for disturbing you.

Is there a solution to this problem?

**Comment by simonpcouch** [comment]
Hey there, I haven't yet been able to make time for this—will chime in when I do. Would be glad to review a PR addressing this in the meantime. :)

**Comment by amazongodman** [comment]
@simonpcouch 


I'm sorry to rush you.
Thank you for the link.
I will continue to support you.

**Comment by simonpcouch** [comment]
Thanks for your patience here!

It looks like the actual issue here is that `collect_parameters` isn’t keeping track of column names correctly in the context of logistic regression. The issue can be reproduced with only the `glmnet` grid:

``` r
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
library(finetune)
library(stacks)

data(two_class_dat, package = "modeldata")

set.seed(123)
folds <- bootstraps(two_class_dat, times = 10)

glmnet_recipe <- 
  recipe(formula = Class ~ ., data = two_class_dat) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_predictors(), -all_nominal()) 

glmnet_spec <- 
  logistic_reg(penalty = tune(), mixture = tune()) %>% 
  set_mode("classification") %>% 
  set_engine("glmnet") 

glmnet_workflow <- 
  workflow() %>% 
  add_recipe(glmnet_recipe) %>% 
  add_model(glmnet_spec) 

glmnet_grid <- 
  tidyr::crossing(
    penalty = 10^seq(-6, -1, length.out = 20), 
    mixture = c(0.05, 0.2, 0.4, 0.6, 0.8, 1)
  ) 

glmnet_tune <- 
  tune_grid(
    glmnet_workflow,
    resamples = folds,
    grid = glmnet_grid,
    control = control_grid(save_pred = T,save_workflow = T)
  ) 

stack_model <- 
  stacks() %>%
  add_candidates(glmnet_tune, name = "tune")
#> Warning: Predictions from 116 candidates were identical to those from existing
#> * candidates and were removed from the data stack.

fit_stack <- stack_model %>% 
  blend_predictions() %>% 
  fit_members()

collect_parameters(fit_stack, "tune")
#> # A tibble: 120 × 4
#>    member        penalty mixture  coef
#>    <chr>           <dbl>   <dbl> <dbl>
#>  1 tune_1_001 0.000001      0.05    NA
#>  2 tune_1_002 0.00000183    0.05    NA
#>  3 tune_1_003 0.00000336    0.05    NA
#>  4 tune_1_004 0.00000616    0.05    NA
#>  5 tune_1_005 0.0000113     0.05    NA
#>  6 tune_1_006 0.0000207     0.05    NA
#>  7 tune_1_007 0.0000379     0.05    NA
#>  8 tune_1_008 0.0000695     0.05    NA
#>  9 tune_1_009 0.000127      0.05    NA
#> 10 tune_1_010 0.000234      0.05    NA
#> # … with 110 more rows
```

The issue arises in the `.get_glmn_coefs` internal function. The condition `is.list(x$estimate)` isn’t `TRUE` because the data structure there for a 2 class problem looks the same as it does in the regression context even though coefficients are implicitly associated with an outcome class.

Working on a fix. :)

<sup>Created on 2022-01-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by simonpcouch** [comment]
Huzzah!

``` r
library(tidymodels)
#> Registered S3 method overwritten by 'tune':
#>   method                   from   
#>   required_pkgs.model_spec parsnip
library(finetune)
library(stacks)

data(two_class_dat, package = "modeldata")

set.seed(123)
folds <- bootstraps(two_class_dat, times = 10)

rf_spec <- rand_forest(mtry = tune(), trees = tune(), min_n = tune()) %>%
  set_mode("classification") %>%
  set_engine("ranger")

rf_wf <- workflow(Class ~ ., rf_spec)
ctrl_stck <- control_race(save_pred = TRUE, save_workflow = TRUE)

doParallel::registerDoParallel()
set.seed(234)
race_res <- tune_race_anova(rf_wf, 
                            resamples = folds, 
                            grid = 10, 
                            control = ctrl_stck)
#> i Creating pre-processing data to finalize unknown parameter: mtry

glmnet_recipe <- 
  recipe(formula = Class ~ ., data = two_class_dat) %>% 
  step_zv(all_predictors()) %>% 
  step_normalize(all_predictors(), -all_nominal()) 

glmnet_spec <- 
  logistic_reg(penalty = tune(), mixture = tune()) %>% 
  set_mode("classification") %>% 
  set_engine("glmnet") 

glmnet_workflow <- 
  workflow() %>% 
  add_recipe(glmnet_recipe) %>% 
  add_model(glmnet_spec) 

glmnet_grid <- 
  tidyr::crossing(
    penalty = 10^seq(-6, -1, length.out = 20), 
    mixture = c(0.05, 0.2, 0.4, 0.6, 0.8, 1)
  ) 

glmnet_tune <- 
  tune_grid(
    glmnet_workflow,
    resamples = folds,
    grid = glmnet_grid,
    control = control_grid(save_pred = T,save_workflow = T)
  ) 

stack_model <- 
  stacks() %>%
  add_candidates(race_res, name = "race") %>% 
  add_candidates(glmnet_tune, name = "tune")
#> Warning: Predictions from 116 candidates were identical to those from existing
#> * candidates and were removed from the data stack.

fit_stack <- stack_model %>% 
  blend_predictions() %>% 
  fit_members()

collect_parameters(fit_stack, "race")
#> # A tibble: 1 × 6
#>   member     mtry trees min_n terms                   coef
#>   <chr>     <int> <int> <int> <chr>                  <dbl>
#> 1 race_1_03     1  1168    33 .pred_Class2_race_1_03 0.251

collect_parameters(fit_stack, "tune")
#> # A tibble: 62 × 5
#>    member      penalty mixture terms                    coef
#>    <chr>         <dbl>   <dbl> <chr>                   <dbl>
#>  1 tune_1_001 0.000001    0.05 .pred_Class2_tune_1_001  3.04
#>  2 tune_1_012 0.000785    0.05 .pred_Class2_tune_1_012  0   
#>  3 tune_1_013 0.00144     0.05 .pred_Class2_tune_1_013  0   
#>  4 tune_1_014 0.00264     0.05 .pred_Class2_tune_1_014  0   
#>  5 tune_1_015 0.00483     0.05 .pred_Class2_tune_1_015  0   
#>  6 tune_1_016 0.00886     0.05 .pred_Class2_tune_1_016  0   
#>  7 tune_1_017 0.0162      0.05 .pred_Class2_tune_1_017  0   
#>  8 tune_1_018 0.0298      0.05 .pred_Class2_tune_1_018  0   
#>  9 tune_1_019 0.0546      0.05 .pred_Class2_tune_1_019  0   
#> 10 tune_1_020 0.1         0.05 .pred_Class2_tune_1_020  0   
#> # … with 52 more rows
```

Hope this does the trick for ya.

<sup>Created on 2022-01-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>
